<a href="https://colab.research.google.com/github/kalxdoc/Research_pac1/blob/main/deep_learning_self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cpu


In [3]:
my_list=[[1,2,3],[2,3,4]]
tensor=torch.tensor(my_list)
tensor

tensor([[1, 2, 3],
        [2, 3, 4]])

In [4]:
import torch.nn as nn

In [5]:
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
linear_layer = nn.Linear(
                         in_features=3,
                         out_features=2
                         )
output_tensor = linear_layer(input_tensor)
print(output_tensor)

tensor([[0.5150, 0.1123]], grad_fn=<AddmmBackward0>)


In [6]:
in_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1,2,4]])
model=nn.Sequential(nn.Linear(10,20),
                    nn.Linear(20,30),
                    nn.Linear(30,10),
                    nn.Linear(10,2))
output_tensor=model(in_tensor)
print(output_tensor)
total=0
for parameter in model.parameters():
  total+=parameter.numel()
print(total)

tensor([[ 0.6767, -0.5472]], grad_fn=<AddmmBackward0>)
1182


In [7]:
input_tensor = torch.tensor([[2.4]])
input_tensor2 = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)
softmax = nn.Softmax()
probabilities = softmax(input_tensor2)
print(probabilities)

tensor([[0.9168]])
tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py:1779: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [8]:
input_tensor3 = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax(dim=-1)
)

output = model(input_tensor3)
print(output)

tensor([[0.1322, 0.1993, 0.3930, 0.2755]], grad_fn=<SoftmaxBackward0>)


In [9]:
import numpy as np
import torch.nn.functional as F

y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes=3)

print("One-hot vector using NumPy:", one_hot_numpy)
print("One-hot vector using PyTorch:", one_hot_pytorch)

One-hot vector using NumPy: [0 1 0]
One-hot vector using PyTorch: tensor([0, 1, 0])


In [10]:
# Define dummy inputs and targets to make the model run
sample = torch.randn(1, 16)
target = torch.tensor([1])

model = nn.Sequential(nn.Linear(16, 8),
                       nn.Linear(8, 4),
                      nn.Linear(4, 2))
prediction = model(sample)

# Calculate the loss and gradients using nn.CrossEntropyLoss
criterion = nn.CrossEntropyLoss()
loss = criterion(prediction, target)
loss.backward()

print("Loss:", loss.item())
print(model[0].weight.grad)
model[0].bias.grad
model[1].weight.grad
model[1].bias.grad
model[2].weight.grad
model[2].bias.grad

# Learning rate is typically small
lr = 0.001
# Update the weights
weight = model[0].weight
weight_grad = model[0].weight.grad
weight = weight - lr * weight_grad
# Update the biases
bias = model[0].bias
bias_grad = model[0].bias.grad
bias = bias - lr * bias_grad

Loss: 1.2040969133377075
tensor([[ 0.0474, -0.0069, -0.0164,  0.0342,  0.0057, -0.0190, -0.0670, -0.0379,
         -0.0684, -0.0557, -0.0365,  0.0273,  0.0212, -0.0756,  0.0942, -0.0126],
        [-0.1456,  0.0211,  0.0506, -0.1051, -0.0174,  0.0585,  0.2059,  0.1165,
          0.2103,  0.1712,  0.1121, -0.0839, -0.0653,  0.2324, -0.2895,  0.0388],
        [ 0.0446, -0.0065, -0.0155,  0.0322,  0.0053, -0.0179, -0.0631, -0.0357,
         -0.0644, -0.0524, -0.0343,  0.0257,  0.0200, -0.0712,  0.0886, -0.0119],
        [ 0.2013, -0.0292, -0.0699,  0.1453,  0.0240, -0.0808, -0.2847, -0.1610,
         -0.2908, -0.2367, -0.1550,  0.1160,  0.0903, -0.3213,  0.4002, -0.0537],
        [ 0.0864, -0.0125, -0.0300,  0.0624,  0.0103, -0.0347, -0.1222, -0.0691,
         -0.1248, -0.1016, -0.0666,  0.0498,  0.0387, -0.1379,  0.1718, -0.0230],
        [-0.1179,  0.0171,  0.0409, -0.0851, -0.0141,  0.0473,  0.1668,  0.0943,
          0.1703,  0.1386,  0.0908, -0.0679, -0.0529,  0.1882, -0.2344,  0.0314

In [22]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import TensorDataset

data = {
    "animal_name": ["sparrow", "eagle", "cat", "dog", "lizard"],
    "hair": [0, 0, 1, 1, 0],
    "feathers": [1, 1, 0, 0, 0],
    "eggs": [1, 1, 0, 0, 1],
    "milk": [0, 0, 1, 1, 0],
    "predator": [0, 1, 1, 0, 1],
    "legs": [2, 2, 4, 4, 4],
    "tail": [1, 1, 1, 1, 1],
    "type": [0, 0, 1, 1, 2],
}

animals=pd.DataFrame(data)
X = animals.iloc[:, 1:-1].to_numpy()
y = animals.iloc[:, -1].to_numpy()
print('X:', X)
print('y:', y )

dataset = TensorDataset(torch.tensor(X),torch.tensor(y))

input_sample, label_sample = dataset[0]
print('Input sample:', input_sample)
print('Label sample:', label_sample)

from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Iterate over the dataloader
for batch_inputs, batch_labels in dataloader:
    print('batch_inputs:', batch_inputs)
    print('batch_labels:', batch_labels)

X: [[0 1 1 0 0 2 1]
 [0 1 1 0 1 2 1]
 [1 0 0 1 1 4 1]
 [1 0 0 1 0 4 1]
 [0 0 1 0 1 4 1]]
y: [0 0 1 1 2]
Input sample: tensor([0, 1, 1, 0, 0, 2, 1])
Label sample: tensor(0)
batch_inputs: tensor([[0, 0, 1, 0, 1, 4, 1],
        [0, 1, 1, 0, 0, 2, 1]])
batch_labels: tensor([2, 0])
batch_inputs: tensor([[0, 1, 1, 0, 1, 2, 1],
        [1, 0, 0, 1, 0, 4, 1]])
batch_labels: tensor([0, 1])
batch_inputs: tensor([[1, 0, 0, 1, 1, 4, 1]])
batch_labels: tensor([1])
