<a href="https://colab.research.google.com/github/kalxdoc/Research_pac1/blob/main/deep_learning_self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cpu


In [3]:
my_list=[[1,2,3],[2,3,4]]
tensor=torch.tensor(my_list)
tensor

tensor([[1, 2, 3],
        [2, 3, 4]])

In [4]:
import torch.nn as nn

In [5]:
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
linear_layer = nn.Linear(
                         in_features=3,
                         out_features=2
                         )
output_tensor = linear_layer(input_tensor)
print(output_tensor)

tensor([[-0.5463, -0.7207]], grad_fn=<AddmmBackward0>)


In [6]:
in_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1,2,4]])
model=nn.Sequential(nn.Linear(10,20),
                    nn.Linear(20,30),
                    nn.Linear(30,10),
                    nn.Linear(10,2))
output_tensor=model(in_tensor)
print(output_tensor)
total=0
for parameter in model.parameters():
  total+=parameter.numel()
print(total)

tensor([[ 0.8068, -0.1650]], grad_fn=<AddmmBackward0>)
1182


In [7]:
input_tensor = torch.tensor([[2.4]])
input_tensor2 = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)
softmax = nn.Softmax()
probabilities = softmax(input_tensor2)
print(probabilities)

tensor([[0.9168]])
tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/usr/local/lib/python3.13/dist-packages/torch/nn/modules/module.py:1779: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [8]:
input_tensor3 = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax(dim=-1)
)

output = model(input_tensor3)
print(output)

tensor([[0.3170, 0.1139, 0.0732, 0.4959]], grad_fn=<SoftmaxBackward0>)


In [11]:
import numpy as np
import torch.nn.functional as F

y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes=3)

print("One-hot vector using NumPy:", one_hot_numpy)
print("One-hot vector using PyTorch:", one_hot_pytorch)

One-hot vector using NumPy: [0 1 0]
One-hot vector using PyTorch: tensor([0, 1, 0])
