<a href="https://colab.research.google.com/github/kalxdoc/Research_pac1/blob/main/deep_learning_self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cpu


In [3]:
my_list=[[1,2,3],[2,3,4]]
tensor=torch.tensor(my_list)
tensor

tensor([[1, 2, 3],
        [2, 3, 4]])

In [4]:
import torch.nn as nn

In [7]:
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
linear_layer = nn.Linear(
                         in_features=3,
                         out_features=2
                         )
output_tensor = linear_layer(input_tensor)
print(output_tensor)

tensor([[-0.2146, -0.1317]], grad_fn=<AddmmBackward0>)


In [14]:
in_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1,2,4]])
model=nn.Sequential(nn.Linear(10,20),
                    nn.Linear(20,30),
                    nn.Linear(30,10),
                    nn.Linear(10,2))
output_tensor=model(in_tensor)
print(output_tensor)

tensor([[ 0.6081, -0.5055]], grad_fn=<AddmmBackward0>)
